/**
 * Zones configuration for agent
 * Connects to master server
 */

object Endpoint "@@MASTER_HOST@@" {
  host = "@@MASTER_HOST@@"
  port = "@@MASTER_PORT@@"
}

object Zone "master" {
  endpoints = [ "@@MASTER_HOST@@" ]
}

object Endpoint "@@AGENT_NAME@@" {
}

object Zone "default" {
  parent = "master"
  endpoints = [ "@@AGENT_NAME@@" ]
}
