PKG_NAME = libgeos
PKG_VERS = 3.9.6
PKG_EXT = tar.bz2
PKG_DIST_NAME = geos-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://download.osgeo.org/geos
PKG_DIR = geos-$(PKG_VERS)

HOMEPAGE = https://libgeos.org/
COMMENT = GEOS (Geometry Engine - Open Source) is a C/C++ library for computational geometry
LICENSE = LGPL-2.1

# GEOS uses CMake
include ../../mk/spksrc.cross-cmake.mk
